// ROS message includes
#include "ros/ros.h"
#include <sensor_msgs/Imu.h>
#include <geometry_msgs/Twist.h>
#include <geometry_msgs/Pose2D.h>

/* protected region user include files on begin */
/* protected region user include files end */

class common_odom_estimation_config
{
public:
    int enable_imu;
    int enable_fake;
    int enable_beacon;
};

class common_odom_estimation_data
{
// autogenerated: don't touch this class
public:
    //input data
    sensor_msgs::Imu in_imu;
    geometry_msgs::Twist in_cmd_vel;
    geometry_msgs::Pose2D in_beacon;
    //output data
};

class common_odom_estimation_impl
{
    /* protected region user member variables on begin */
    /* protected region user member variables end */

public:
    common_odom_estimation_impl() 
    {
        /* protected region user constructor on begin */
        /* protected region user constructor end */
    }

    void configure(common_odom_estimation_config config) 
    {
        /* protected region user configure on begin */
        /* protected region user configure end */
    }

    void update(common_odom_estimation_data &data, common_odom_estimation_config config)
    {
        /* protected region user update on begin */
        /* protected region user update end */
    }

    void topicCallback_imu(const sensor_msgs::Imu::ConstPtr& msg)
    {
        /* protected region user implementation of subscribe callback for imu on begin */
        /* protected region user implementation of subscribe callback for imu end */
    }
    void topicCallback_cmd_vel(const geometry_msgs::Twist::ConstPtr& msg)
    {
        /* protected region user implementation of subscribe callback for cmd_vel on begin */
        /* protected region user implementation of subscribe callback for cmd_vel end */
    }
    void topicCallback_beacon(const geometry_msgs::Pose2D::ConstPtr& msg)
    {
        /* protected region user implementation of subscribe callback for beacon on begin */
        /* protected region user implementation of subscribe callback for beacon end */
    }



    /* protected region user additional functions on begin */
    /* protected region user additional functions end */
};
